defaultPortal: dev
portals:
  - name: dev
    portalId: 123
    authType: 'apikey'
    apiKey: 'xxxxxx-xxxxx-xxxxx-xxxxx-xxxxx'
  - name: staging
    portalId: 123
    authType: oauth2
    auth:
      clientId: 8e9bac50-3ace-4c7d-bcfe-79e6e9954ca5
      clientSecret: 9dfd14dd-d613-4f1f-b93f-614e76b44519
      scopes:
        - content
      tokenInfo:
        expiresAt: '2019-09-18T15:05:07.184Z'
        refreshToken: a2aa1aed-8041-444c-b787-47c3c2e21c66
        accessToken: >-
          COf16KnULRICAgEYqPD7AiDdg7sDKOuZDDIZAC29vH0OTMEE-LLZnE2YaIjmwY9_fDWzxToQADEAQf8HAAAAAIAAAGB4z0IZAC29vH3ruOel9vwypnSNXJQwuleHDDw8VA
